### PR TITLE
Refactor rpc. Split lib-rpc into lib-rpc-app and lib-rpc-core

### PR DESCRIPTION
**Pull request by vamsi-juvvi**
I am proposing to move `agent_rpc.rs`, `conv_rpc.rs` which are like a demo implementation on top of the core macro: `generate_common_rpc_fns`.

This will allow me to create a new `crates/lib-rpc-myapp` along the lines of `crates/lib-rpc-app`. Since I will not be editing framework (_meaning `rust10x/rust-web-app`_) syncing my fork from upstream will not demand careful look at diffs.

If @jeremychone would rather I take a different approach, I am happy to oblige. I am hoping you find this acceptable or are able to guide me along to a different approach more acceptable to you.

The moves are straightforward. 
 - `lib-rpc/rpcs/agent_rpc.rs` → `lib-rpc-app/rpcs/agent_rpc.rs`
 - `lib-rpc/rpcs/conv_rpc.rs` → `lib-rpc-app/rpcs/conv_rpc.rs`
 
I correspondingly moved `all_rpc_router_builder`  from `lib-rpc/rpcs/mod.rs` → `lib-rpc-app/rpcs/mod.rs`

The one notable change however is `prelude.rs`. Since this needs to be used from user rpc libs and makes most sense to be at the crate level.

 - moved it from `lib-rpc/rpcs/prelude.rs` to `lib-rpc/prelude.rs`
 - changed `mod prelude.rs` to `pub mod prelude` in `lib.rs`
 - this is now used from conv_rpc etc as `use lib_rpc_core::prelude::*`
 
The rest are just cascading changes to get things to compile.

> I am in two minds about `lib-rpc-app` vs `lib-rpc-demo`.  I feel `lib-rpc-demo` conveys the intent better. I'll make changes before merge if you prefer the demo version as well.

### CODE REVIEW

**Comment by jeremychone** [comment]
I like the direction of the PR. From a quick first scan, it looks pretty good.

I might need some time to review this, but thanks, this is good work, and I will definitely merge it if everything makes sense.

**Comment by vamsi-juvvi** [comment]
Glad you were able to take a quick look. I updated the comment with more notes.

As a first pass, I also want to separate out the rest of the demo items as well. Potentially
 - lib-model-demo (_to take `agent.rs`, `conv_msg.rs`, `conv.rs`, `conv_user.rs` out of `lib-core`_)
 - lib-web-core (_potentially take reusable bits out of services/web-server_)
 
Additionally, i feel that the `lib-core/_dev_utils/dev_db.rs` might be better taken out into it's own `lib-core-demo-db` or some such.
  - Allows less critical attention to PRs affecting those files in the future 
  - Stick that dependency under a `[profile.dev]` so that even accidentally, it never makes it to staging/prod.
  
If you have any guidance along these lines, suggestions for lib names etc. I will be happy to make changes accordingly and send them your way.

**Comment by jeremychone** [comment]
@vamsi-juvvi the lib-core/_dev_utils/... uses some lib-core and is used by lib-core, so something will have to remain there.

Let's leave it there for now. In theory, I agree, but from a pragmatic point of view, I think we have a better net value/complexity ratio like this. We can move it somewhere else when needed. In my way, only lib-core should need those db-utils, as all data calls should go through the model. So, it's not that bad.

**Comment by jeremychone** [comment]
@vamsi-juvvi 

Ok, I just saw the latest commit, and it adds React, which is interesting but not related to the initial intent of the PR.

The React addition is pretty cool, but React is not something I am familiar with (or intend to be familiar with), so it will be hard for me to maintain it when I update the codebase. This is a trick one. 

Anyway, the fact that those two are in the same PR makes this PR tricky to merge. So, I am going to close this PR, but feel free to split them.

I might merge the rpc-core/app PR.

Regarding the **ReactJS** addition, I would be more comfortable adding a link to a fork/branch for people to look at.

**Comment by vamsi-juvvi** [comment]
Hah! Didn't realize I pushed the react stuff into the same branch. Will redo the PRs cleanly and send them back out.

Thanks for taking a look.

**Pull request closed without merging**
